name: TWRP手动编译-milllet
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 安装编译依赖
        run: |
          sudo apt update -y
          sudo apt install -y build-essential bison flex lzop bc zip libssl-dev openjdk-8-jdk

      - name: 直接编译TWRP Recovery
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          make -j$(nproc) recoveryimage

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: milllet_TWRP_7.1
          path: recovery.img
