name: TWRP millet Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 安装编译依赖
        run: |
          sudo apt update -y
          sudo apt install -y git build-essential bison flex lzop bc zip cpio \
          openjdk-8-jdk gcc-9 g++-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90

      - name: 初始化极简TWRP 7.1编译框架
        run: |
          mkdir -p twrp && cd twrp
          # TWRP Recovery主体
          git clone --depth=1 -b android-7.1 https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
          # 必备编译核心
          git clone --depth=1 -b android-7.1 https://github.com/LineageOS/android_build.git build
          git clone --depth=1 -b android-7.1 https://github.com/LineageOS/android_vendor_omni.git vendor/omni

      - name: 导入你的设备仓库
        uses: actions/checkout@v4
        with:
          path: twrp/device/millet

      - name: 执行编译
        run: |
          cd twrp
          source build/envsetup.sh
          lunch omni_millet-userdebug
          make recoveryimage -j$(nproc)

      - name: 上传编译成品
        uses: actions/upload-artifact@v4
        with:
          name: TWRP_millet_7.1
          path: twrp/out/target/product/millet/recovery.img

