name: Build TWRP 7.1

于:
  workflow_dispatch:

jobs:
  build:
    # 换成最容易抢到的运行环境
    runs-on: ubuntu-22.04
    steps:
      - name: Clone source
        uses: actions/checkout@v4

      - name: Install compile dependencies
        run: |
          sudo apt update -y
          sudo apt install -y openjdk-8-jdk build-essential bison flex zip lzop bc libssl-dev

      - name: Compile TWRP
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          source build/envsetup.sh
          #这里我帮你后续写死机型，彻底杜绝问题
          lunch millet-userdebug
          make recoveryimage -j$(nproc)

      - name: Upload recovery.img
        uses: actions/upload-artifact@v3
        with:
          name: TWRP_成品
          path: out/target/product/*/recovery.img
